In [27]:
import torch
import torch.nn as nn

from Exercises_1 import Softmax, SoftmaxStable
from Exercises_2 import Student, Teacher, Doctor, Ward
from Exercise_3 import Stack
from Exercise_4 import Queue

In [15]:
data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim= -1)
output = softmax_function(data)
assert round(output[0].item(), 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

In [16]:
data = torch.tensor([5, 2, 4])
my_sm = Softmax()
output = my_sm(data)
assert round ( output [ -1]. item () , 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

In [17]:
data = torch.tensor([1, 2, 30_000_000])
my_sm = Softmax()
output = my_sm(data)
assert round(output[0].item(), 2) == 0.0
output

tensor([0., 0., nan])

In [18]:
data = torch.Tensor([1, 2, 3])
softmax_function = SoftmaxStable()
output = softmax_function(data)
assert round(output[-1].item(), 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

In [21]:
student1 = Student ( name =" studentZ2023 ", yob =2011 , grade ="6")
assert student1.yob == 2011
student1.describe ()

Student - Name:  studentZ2023  - YoB: 2011 - Grade: 6


In [23]:
teacher1 = Teacher ( name =" teacherZ2023 ", yob =1991 , subject =" History ")
assert teacher1.yob == 1991
teacher1.describe ()

Teacher - Name:  teacherZ2023  - YoB: 1991 - Subject:  History 


In [25]:
doctor1 = Doctor ( name =" doctorZ2023 ", yob =1981 , specialist =" Endocrinologists ")
assert doctor1.yob == 1981
doctor1 . describe ()

Doctor - Name:  doctorZ2023  - YoB: 1981 - Specialist:  Endocrinologists 


In [26]:
student1 = Student(name="studentA", yob=2010, grade="7")
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")

ward1 = Ward(name="Ward1")

ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)

assert ward1.count_doctor() == 1, "The number of doctors should be 1"

doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")
ward1.add_person(doctor2)

print(f"Number of doctors in the ward: {ward1.count_doctor()}")


Number of doctors in the ward: 2


In [28]:
stack1 = Stack ( capacity =5)
stack1 . push (1)
assert stack1 . is_full () == False
stack1 . push (2)
print ( stack1 . is_full () )

False


In [30]:
stack1 = Stack ( capacity =5)
stack1 . push (1)
assert stack1 . is_full () == False
stack1 . push (2)
print ( stack1 . top () )

2


In [31]:
queue1 = Queue ( capacity =5)
queue1 . enqueue (1)
assert queue1 . is_full () == False
queue1 . enqueue (2)
print ( queue1 . is_full () )

False


In [32]:
queue1 = Queue ( capacity =5)
queue1 . enqueue (1)
assert queue1 . is_full () == False
queue1 . enqueue (2)
print ( queue1 . front () )

1


: 